### PR TITLE
Addressing issue #6

### PR DESCRIPTION
**Pull request by rbeesley**
Adds the blur/bloom effect to the text and uses the Retro.hlsl scanlines.

### CODE REVIEW

**Comment by rbeesley** [comment]
I did a little more clean up and I added a hue shifting shader. It's nice on its own at a slow change rate, but it also would be a nice addition to a Retro CRT shader is you wanted to tweak the colors with a "tint" knob.

**Comment by Hammster** [comment]
Hi thanks for the contribution,

The changes on the CRT shader look good, but since the code was taken from the MIT licenced MS repository I would need to add the original MIT licence as will, and make the original CC Zero 1.0 licence invalidate. I will rewrite the function so that this should not be an issue, but this has to wait for tomorrow or the day after.

I like the hue-shift, that can be especially helpful for people with specific color blindness types and xterm colors. Though it would be nicer to have this in a separate PR (Since then I could merge it directly :)), though it's fine if you leave it like this.

**Comment by rbeesley** [comment]
I just kinda got sucked into trying to figure shaders out. And then sucked into color spaces... Have you come up with a good way to debug and write HLSL shaders compatible with Windows Terminal? All my attempts at providing a texture with HLSL editors just yield a black screen and the only way I found to test has been disabling the shader in settings.json, saving, and then reenabling. _Bleh_. I can submit the hueshift.hlsl as a separate PR. I can also keep the blur code as a separate PR so that it can be pulled in at a later time. It doesn't seem to affect much and seems to be the only thing which would affect the licensing since it was pulled directly from retro.hlsl. Other parts were researched from blog posts and papers referenced in the shader, but those don't seem to have licenses attached, so the inline citing probably suffices as best as anything.

**Comment by Hammster** [comment]
Debugging was a pain for me as well, what worked is switching between focus mode and normal mode. 
But maybe it's possible to set up something like https://github.com/dfranx/SHADERed 

I'll review your other PR ASAP

**Comment by rbeesley** [comment]
@Hammster, yeah, I've been trying to get things working with SHADERed, but no luck yet. If I figure it out, I'll put together some documentation on how to use it.

**Comment by rbeesley** [comment]
@Hammster, better than expected:
image

The refresh scan flows the wrong way and a few things aren't working, but I consider this great progress. The nice thing is that I think it only requires a small macro block to switch between the SHADERed and Windows Terminal, and the macro block conditional can be set as part of editing in SHADERed allowing the same .hlsl to be used in both environments without modification.

**Comment by rbeesley** [comment]
@Hammster, there's some boiler plate, but I have a full SHADERed environment for developing shaders and porting them directly to Windows Terminal without any changes:
image

I'm working on documentation right now, but this might be something I'll submit to the Terminal repro.

**Comment by Hammster** [comment]
Wow that's great! Once you've submitted that over please send me a link.

**Comment by rbeesley** [comment]
More than just a test sample... this is CRT transitioned to the new setup:
image

Debug is turned on in SHADERed, but this is just loading the same shader straight into Windows Terminal without changes. If you squint, you'll see that all the steps which apply changes to the CRT have been moved out to separate functions and only transformCurve remains. 
[CRT.zip](https://github.com/Hammster/windows-terminal-shaders/files/6314243/CRT.zip)

I'm pretty sure if you install SHADERed and open this project you'll see it working, however I'll finish writing the documentation for it this evening.

**Pull request closed without merging**
