### PR TITLE
Made curve transform intensity variable

### PR DESCRIPTION
**Pull request by RodneyKoolman**
Added CURVE_INTENSITY variable (default 1)

Modified get ratio to apply CURVE_INTENSITY

Tested and works

### CODE REVIEW

**Review by rbeesley — APPROVED** [review]
Seems to work. I'm not sure what @Hammster had in mind when that initial comment was made, but this does seem to control the intensity of the curve.

**Review by rbeesley — CHANGES_REQUESTED** [review]
While these changes work. Update the documentation in the README.md to explain how to use this setting.

**Comment by RodneyKoolman** [comment]
Updated the documentation. @rbeesley

**Comment by Hammster** [comment]
Looks good to me, thanks for your contribution and also thanks @rbeesley for your continuous support 👍 ❤️

**Pull request merged**
