### PR TITLE
Crt.hlsl

### PR DESCRIPTION
**Pull request by rbeesley**
Updates crt.hlsl to support different grayscale conversion strategies. Retro.hlsl components removed.

### CODE REVIEW

**Comment by rbeesley** [comment]
I think I have more coming for this. I think I was handling gamma incorrectly and have updated gleam and lumanince. They were being overblown and this new change fits the brights better although with lumanince darks seem more crushed. I think this is because Vintage just has dark darks, but it is probably well suited for something like Campbell. I also think I'm close to making the shader work directly on SHADERed and Windows Terminal without modifications, so those would both be nice additions.

**Comment by Hammster** [comment]
I'm going to take a proper look it this week :)

**Comment by rbeesley** [comment]
@Hammster, look at #11 first. If you're successful getting that to work then I'll remove the scanline portion and commit those changes back to this PR since that is what is left. You could reimplement your scanline, but with the bloom and blur, I'm actually pretty without that piece of that's what we need to get the whole PR committed.

**Comment by Hammster** [comment]
Hey #11 worked fine for me, i'm fine with your implementation of scan lines too :) Give me just a quick feeback if the code in here is still something you want to adjust since #11 is meged

**Comment by rbeesley** [comment]
Closing this because you brought in #11.

**Pull request closed without merging**
